### PR TITLE
fix for issue #8

### PR DESCRIPTION
**Pull request by diddy81**
fix for information not showing for Latest Releases (Trakt) and Next Episodes

### CODE REVIEW

**Comment by drinfernoo** [comment]
What information does this give us exactly?

**Comment by diddy81** [comment]
Openmeta currently does not pull the plot for the latest releases list or next episodes list this will fix that

**Comment by diddy81** [comment]
drinfernoo ive added default player and context menu to choose a player i also fixed the context menus showing on widgets by adding the missing meta data

**Comment by drinfernoo** [comment]
In coming updates, player interactions, metadata, context menus, widgets, and many other things have been fixed already. If this PR still applies after further testing of internal changes, a merge is likely.

**Comment by diddy81** [comment]
Yes I have seen in the issues about 2.0 milestones but having not seen any of the items being implemented in the develop branch wasn't sure how much had been done already and the parts I have done are just things I wanted implemented and wanted to share with your guys any idea when the 2.0 update will be ready or if I can be any help getting it ready?

**Comment by drinfernoo** [comment]
There isn't any ETA for a future release, but I'm testing this in an effort to go ahead and merge it.

I can confirm your fixes for metadata on Latest Releases and Next Episodes are working, but using the `?extended=full` argument makes it take a *very long time to load those lists.

With regards to context menus, there's still something funky going on here, as the menus inside OpenMeta have duplicated options, and the ones on widgets are still missing options.

Your implementation of default players does appear to be working smoothly for me, including the changing defaults back and forth and choosing a different option besides the set default.

If you can figure out how to get the context menus inside the add-on to not have duplicated options, I'll merge this 👍

**Comment by diddy81** [comment]
Close kodi and reopen it context menus should reset and be correct

**Comment by diddy81** [comment]
Yep I see the error I made with the duplicate   menus in openmeta I can push a fix for that and will look at changing the full meta to reduce loading time

**Comment by diddy81** [comment]
fixed the context menus however the meta data will need to stay as full as the only other level i could find documentation for does not return the plot as far as i can see

**Comment by diddy81** [comment]
Hay drinfernoo just noticed you said some options are missing in the widget context menus could you tell me what's missing or is it just the 'use default player' option in a openmeta widget that is missing if it is it should be like that as just clicking the item will load the default player

**Comment by drinfernoo** [comment]
Try pointing a widget at a menu of TV Shows 😉

**Comment by diddy81** [comment]
got openinfo showing on tv show widgets just clicking will open season view 
are you wanting the use/choose player items in the context menus too as it will auto play season 1 episode 1 or is just having openinfo what you want

**Comment by SOOTTV** [comment]
@diddy81 been testing out your changes. Love the default player, works great. One thing you fixed, not sure if you're aware; widgets using landscape layout would take a poster image and squeeze it into the landscape box, which looked terrible. You've fixed that issue but only for rows showing movies, I'm wondering if you could do the same for TV shows if you know how you did it?

**Comment by diddy81** [comment]
@SoulTV  no idea how i fixed that I didnt make any changes to images at all unless its just because i added the mediatype tag to movies but I'm struggling to reproduce what your describing could you tell me what skin and widget settings you are using 

if it is the mediatype tag i have now added that to tv shows and will be in my next push just waiting to hear back from @drinfernoo about the tv show context menus that he would like then I will make the next update

**Comment by SOOTTV** [comment]
@diddy81 I'm using Bingie v1.02 by Cartman.dos as my skin. Here's the repo: https://github.com/cartmandos/repository.bingie If you change the homepage widget layout to landscape (should be the default) and add an OpenMeta widget for TV Shows and Movies, you'll definitely see what I'm talking about. I can also preconfigure the userdata file for you if that helps? I'm assuming this bug would be present across all Titan based skins. Hopefully the mediatype tag fixes that

Also, to @drinfernoo 's point about the TV Show widget, on my build at least, Movie widgets have a context menu and TV Show widgets don't have one at all

Quick question, is there a way to download the files so I can just copy and paste them in place? I've been copying the text from each one and replacing the text in the files to test stuff out

**Comment by drinfernoo** [comment]
@SoulTV If you go to https://www.github.com/diddy81/plugin.video.openmeta/, you can download the zip with his changes.

**Comment by diddy81** [comment]
I'll take a look at the skin see what I can do 

The TV show context menu will be enabled in my next push 

And @drinfernoo ninjaed me lol

**Comment by SOOTTV** [comment]
@diddy81 The context is working great for me on tv show widgets. Whatever you did fixed the landscape/ portrait problem with my skin. Thx!

Idk if this is complicated but, is there any way you could implement a toggle in settings to flatten seasons?

**Review by drinfernoo — CHANGES_REQUESTED** [review]
Can you make this match the Kodi native setting, allowing for the option to flatten "if only one season"?

Kodi gives the option (for library content, of course) between "Never", "If only one season", and "Always".

I'd actually love to see this as it's own PR too. In general, pull requests should be self-contained features/fixes, rather than a collection of tweaks.

**Comment by SOOTTV** [comment]
@diddy81 I tried to figure out how to add list but couldn't get it to work, could you add these as well?

https://trakt.tv/users/garycrawfordgc/lists/new-shows?sort=added,asc
https://trakt.tv/users/enormoz/lists/netflix
https://trakt.tv/users/enormoz/lists/netflix-movies
https://trakt.tv/users/enormoz/lists/hulu
https://trakt.tv/users/enormoz/lists/amazon

**Comment by diddy81** [comment]
Sorry but I won't be adding any lists unless they have been ok'd by a main dev
You can just like the lists then find them in the my trakt section

**Comment by SOOTTV** [comment]
Ok, I talked drinfernoo earlier about it, let me see if I can get his OK on it. I wanted to add them so that other people could use them in my build without needing my trakt account logged in or needing to like them on their account

**Comment by drinfernoo** [comment]
There's a good reason we don't have many user lists as main sections in the add-on. If any of those lists ever goes down, the user closes their account, or something similar, it'll break the add-on.

The only reason Latest Releases is included is because the development team has been in contact with the curator of that list (and many others), and believe it is a fairly stable arrangement.

**Pull request closed without merging**
