### PR TITLE
Support current undocumented API change from TVDB.

### PR DESCRIPTION
**Pull request by ruinernin**
Support both the old files contained in the zip and the new files in case this
goes back to being "correct".

### CODE REVIEW

**Comment by bg-22** [comment]
To avoid splitting result['aliasnames'] if it is a None type, add:

`if result['aliasnames'] is not None`

to the start of Line 157.

**Review by doccy-doc — CHANGES_REQUESTED** [review]
To avoid attempting to split `result['aliasnames']` if it is a None type, the following should be added to the start of line 157:

`if result['aliasnames'] is not None:`

**Review by SerpentDrago — APPROVED** [review]

**Comment by SerpentDrago** [comment]
@ruinernin  Thanks for the code man , @bg-22  you to for the modifications . with this changes  we dont' need your other pr also right ? 

@ruinernin Everything seems to work with your code and  bg-22 's changes , just wanted you to review the changes before i merge and push to repo

**Comment by doccy-doc** [comment]
Correct. With the changes I requested for @ruinernin 's code, my PR isn't needed. However, @ruinernin makes a good point about making this change broader, allowing it to withstand other empty variables in the future. Not a bad idea considering how TheTVDB has a track record of breaking things like this. I believe PR #53 addresses this.

**Comment by drinfernoo** [comment]
I cherry-picked this into develop... didn't realize it didn't close 😆

**Pull request closed without merging**
